const constants = {
  PLANTS: [
    {
      name: 'garlic',
      tileInfo: 'keeps the vampires away',
      zones: '3 to 8',
      monthsToPlant: ['september', 'october', 'november'],
      expectedHarvestTime: ['may', 'june', 'july'],
      water: '1 to 2 inches per week',
      sun: 'Full sun - at least 6 hours per day',
      friends: [],
      enemies: [],
    },
    {
      name: 'onion',
      tileInfo: 'they go in everything so might as well grow them',
      zones: '3 to 9',
      monthsToPlant: ['february', 'march'],
      expectedHarvestTime: ['july', 'august'],
      water: '1 to 2 inches per week',
      sun: 'Full sun - at least 6 hours per day',
      friends: ['carrot', 'beet', 'lettuce', 'tomato', 'rosemary'],
      enemies: ['asparagus', 'beans', 'peas'],
    },
    {
      name: 'jalapeno pepper',
      tileInfo: 'ouch that\'s hot',
      zones: '5 to 11',
      monthsToPlant: ['january', 'february', 'march'],
      expectedHarvestTime: ['march', 'april', 'may'],
      water: '1 to 2 inches per week, more when hotter',
      sun: 'Full sun - at least 6 hours per day',
      friends: ['basil', 'onion', 'spinach', 'tomato'],
      enemies: ['beans'],
    },
    {
      name: 'potato',
      tileInfo: 'everyone loves potatoes',
      zones: '1 to 7',
      monthsToPlant: ['february', 'march'],
      expectedHarvestTime: ['june'],
      water: '1 to 2 inches per week',
      sun: 'Full sun - at least 6 hours per day',
      friends: [],
      enemies: [],
    },
    {
      name: 'sweet potato',
      tileInfo: 'potato\'s warm-weather-loving relative',
      zones: '3 to 11',
      monthsToPlant: ['march', 'april'],
      expectedHarvestTime: ['july', 'august'],
      water: '1 to 2 inches per week',
      sun: 'Full sun - at least 6 hours per day',
      friends: [],
      enemies: [],
    },
  ],
  DEFAULT_USER_SETTINGS: {
    firstName: '',
    lastName: '',
    hardinessZone: '0',
  },
  TRAITS: {
    zones: 'Ideal Zones for Growing',
    monthsToPlant: 'Ideal Planting Months',
    expectedHarvestTime: 'Expected Time To Harvest',
    water: 'Water Needs',
    sun: 'Sun Needs',
    friends: 'Companion Plants',
    enemies: 'Don\'t Plant Next to These',
  },
};

module.exports = constants;
